### ISSUE TITLE
New command `list` for viewing both local and remote packages

### ISSUE THREAD

**Issue by hrszpuk** [hrszpuk/BorgorClient#5]
## Description
Currently, there is no way to view locally installed packages.
This isn't a major issue but does make checking if a package has been installed a less than enjoyable experience. Furthermore, it would be extremely useful to view a list of packages currently on rps servers. 

## Solution
A `list` command (i.e. `borgor list` or `rps list`) which allows you to view a list of packages.
- Using `list` alone will give every package currently installed in the local package database. 
- `--available` (or `-a`) will list all packages available to download from rps servers. 
- `--not-installed` (or `-n`) will list all packages available to download which aren't currently downloaded

The following flags are used for searching/filtering the list results. This means if `--available` or `--not-installed` are not used then it will filter results from the local package database, otherwise, if they are used, then it will filter results from the entire rps package database.
- `--author` will list all packages by the given author
- `--version` will list all packages with the given version number
- `--name` will list all packages with the given name (kinda useless but consistency)
- `--contains` will list all packages that contain the given phrase in their description or name.

**Comment by hrszpuk** [comment]
If RPS server *is* rewritten then it would be nice to have some extra functionality built-in server-side for this kind of thing.

**Comment by mauro-balades** [comment]
Hey there!

Looks like you are new to contributing to rect. Imma send you a list of rules to make sure you are respectful to others. Have a recty day!


[rules](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by hrszpuk** [comment]
The basic parts of this are done. Just need to add the flags.
